#!/bin/sh

# Load system X11 scripts
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Load user X resources
[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources

# Start i3
exec i3
